spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: mysecretpassword
    driver-class-name: org.postgresql.Driver

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true
    url: jdbc:postgresql://localhost:5432/mydatabase
    user: myuser
    password: mysecretpassword