version: '3'
services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data